# Generated by Django 5.2.1 on 2025-05-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_add_userprofile"),
    ]

    operations = []
